basic_app/urls.py
from basic_app import views
from django.conf.urls import url
from django.urls import path

app_name='basic_app'

urlpatterns=[
    path('register/',views.register,name="register"),
    path('user_login/',views.user_login,name="user_login"),
    path('git_user_search/',views.git_user_search,name="git_user_search"),
    path('about_me/',views.contact_msg_store,name="about_me"),
    path('git_user_search/<str:user>/',views.git_user_info,name="user_profile"),
    path('git_user_search/<str:user>/<str:repo_name>/',views.commit_info,name="commit_history"),
    path('git_user_search/search_again',views.git_user_search,name="search_again_user")

]

learning_users/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.urls import path
from basic_app import views
urlpatterns = [
    path('',views.index,name="index"),
    
    path('basic_app/',include('basic_app.urls')),
    path('admin/', admin.site.urls),
    path('logout/',views.user_logout,name="logout"),
    path('special/',views.special,name="special"),

]

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
#it is used to add additional attributes directly using User class may cause errors in database
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    #additional classes or attributes
    portfolio_site=models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)
    def __str__(self):
        return self.user.username
        #username is the default attribute of the user that we created in line 7
#new part from here
class GithubUsers(models.Model):
    #used for the user input for git search
    git_username=models.CharField(max_length=264)
    def __str__(self):
        return self.git_username

class Contact(models.Model):
    #used to for contacting me 
    contact_message=models.CharField(max_length=1500)

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo,GithubUsers,Contact

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model=User
        fields=('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('portfolio_site','profile_pic')

class GithubUsersForm(forms.ModelForm):
    class Meta():
        model=GithubUsers
        fields=('git_username',)

class ContactForm(forms.ModelForm):
    class Meta():
        model=Contact
        fields=('contact_message',)

basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm,UserProfileInfoForm,GithubUsersForm,ContactForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate,login,logout
import json
import requests
# Create your views here.
def index(request):
    return render(request,"basic_app/index.html")

@login_required
def special(request):
    return HttpResponse("You are logged in")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered=False
    if request.method=="POST":
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()

            profile=profile_form.save(commit=False)
            profile.user=user
            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']
            profile.save()
            registered=True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm()
    return render(request,'basic_app/registration.html',
                            {'user_form':user_form,
                             'profile_form':profile_form,
                             'registered':registered,})



def user_login(request):
    if request.method=="POST":
        username=request.POST.get('username')
        password=request.POST.get('password')

        user=authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("someone tried to login and failed!")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("Invalid login details supplied")
    else:
        return render(request,'basic_app/login.html',{})


#takes the input from user searches through the search api
@login_required
def git_user_search(request):
    found=False
    if request.method=="POST":
        git_username_form=GithubUsersForm(data=request.POST)
        if git_username_form.is_valid():
            github_user=git_username_form.save()
            url=requests.get("https://api.github.com/search/users?q={} in:fullname&per_page=100".format(github_user))
            json_object=url.json()
            count=json_object["total_count"]
            if count==0:
                found=True
                return render(request,'basic_app/search_user.html',{"git_username_form":GithubUsersForm(),"found":found})
            else:
                return render(request,'basic_app/user_list.html',{"user_search_list":json_object})
        else:
            return HttpResponse("INVALID FORM")
    else:
        return render(request,'basic_app/search_user.html',{"git_username_form":GithubUsersForm()})



#using dynamic url the input taken from the user_list.html page it goes to urls.py from there it calls git_user_info to display the details on user_info.html
@login_required
def git_user_info(request,user):
        url_1=requests.get("https://api.github.com/users/{username}".format(username=user))
        url_2=requests.get("https://api.github.com/users/{username}/repos".format(username=user))
        json_object_1=url_1.json()
        json_object_2=url_2.json()
        return render(request,'basic_app/user_info.html',{"user_info":json_object_1,"repo_info":json_object_2})


#similar to the previous func using the commit api the info of commits is displayed on commit_data.html
@login_required
def commit_info(request,user,repo_name):
    url3=requests.get("https://api.github.com/repos/{username}/{repo}/commits".format(username=user,repo=repo_name))
    json_object_3=url3.json()
    return render(request,'basic_app/commit_data.html',{"user_commit":json_object_3,"repo_name":repo_name})

#An additional thing added to contact me or send a message to me 
@login_required
def contact_msg_store(request):
    enquiry=False
    if request.method=="POST":
        contact_message_1=ContactForm(data=request.POST)
        if contact_message_1.is_valid():
            contact_me_message=contact_message_1.save()
            contact_me_message.save()
            enquiry=True
    else:
        contact_message_1=ContactForm()
    return render(request,'basic_app/contact_me.html',{"contact_message_1":contact_message_1,"enquiry":enquiry})

templates/basic_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type='text/css' href="{% static 'css/mycss.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-light navbar-fixed-top navbar-expand-lg" style="background: white;">
          <div class="navbar-header">
            <a class="navbar-brand" href="#"><strong>UserScannerViewer</strong></a>
          </div>
          <ul class="nav navbar-nav" >
            <li><a  class="navbar-link" href="{% url 'index' %}"><strong>Home</strong></a></li>
            <li><a  class="navbar-link" href="{% url 'basic_app:about_me' %}"><strong>About Me</strong></a></li>
            <li><a  class="navbar-link" href="{% url 'admin:index' %}"><strong>Admin</strong></a></li>
          </ul>
          {% if user.is_authenticated %}
          <ul class="nav navbar-nav navbar-right">
            <li><a  class="navbar-link" href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
            <li><a id="x1" class="navbar-link" href="{% url 'basic_app:git_user_search' %}"><span class="glyphicon glyphicon-search"></span> Search User</a></li>
          </ul>
          {% else %}
          <ul class="nav navbar-nav navbar-right">
            <li><a id="x1" class="navbar-link" href="{% url 'basic_app:register' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
            <li><a id="x1" class="navbar-link" href="{% url 'basic_app:user_login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
          </ul>
          {% endif %}
      </nav>
    </div>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

templates/basic_app/commit_data.html
{% extends "basic_app/base.html" %}
{% load staticfiles %}
{% block body_block %}

  <h2 id="x7">Repo Name:{{repo_name}}</h2>
  {% for obj in user_commit %}

  <div class="list-group">
    <div class="list-group-item">
      <h3><ins>Commit Author</ins>:  {{ obj.commit.author.name }}</h3>
      <h3><ins>Commit Message</ins>:  "{{ obj.commit.message }}"</h3>
      <h3><ins>Commit Date</ins>:  {{ obj.commit.author.date }}</h3>
    </div>
  </div>
  <br>
  <br>
  {% endfor %}

{% endblock %}

templates/basic_app/contact_me.html
{% extends "basic_app/base.html" %}

{% block body_block %}
<div class="jumbotron">
  <h2>Name:PARAG VAID</h2>
  <h3>Contact Me:   <a href="https://github.com/parag1999"><img src="https://assets-cdn.github.com/images/modules/logos_page/GitHub-Mark.png" class="img-circle" width="30px" height="30px"></a></h3>
  {% if enquiry %}
  <h3>Thank You For Enquiring will get to you as soon as possible</h3>
  {% else %}
  <h3>Enter Your query here</h3>
    <form action="{% url 'basic_app:about_me' %}" method="post">
      {{contact_message_1.as_p}}
      {% csrf_token %}
      <input type="submit" class="btn btn-primary" value="Submit">
    </form>
  {% endif %}

</div>
{% endblock %}

templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="container">
  <br>
  <br>
  <h1 id="x4">Welcome!</h1>
  <br>
  <br>
  <br>
  <h3 id="x2">Hey Guys! My name is PARAG and I have just learnt the basics of Django
     and as a project I have made a site where you can sign up, login, logout and search
      for any github users, see their profile, repositories and commits using api's.</h3>
</div>
{% endblock %}

templates/basic_app/login.html
{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
  <h1>Please Login</h1>
  <form  action="{% url 'basic_app:user_login' %}" method="post">
      {% csrf_token %}
      <h3><label for="username">Username:</label>
      <input type="text" name="username" placeholder="Enter Username"></h3>
      <h3><label for="password">Password:</label>
      <input type="password" name="password"></h3>
      <h3 id="x6"><input type="submit" class="button" value="Login"></h3>
  </form>
</div>

{% endblock %}

templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
{% load staticfiles %}
{% block body_block %}

<div class="jumbotron">
  {% if registered %}
    <h1>Thank You for registering!</h1>
  {% else %}
    <h2>Register Here!</h2>
    <h3>Fill out the form:</h3>
    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{user_form.as_p}}
      {{profile_form.as_p}}
      <h3 id="x6"><input type="submit" class="btn btn-default btn-block" value="Sign up"></h3>
    </form>
  {% endif %}

</div>

{% endblock %}

templates/basic_app/search_user.html
{% extends "basic_app/base.html" %}

{% block body_block %}
  <h1 id="x3">SEARCH HERE!</h1>
    <form class="sample" method="POST">
      {% csrf_token %}
      <h4>{{git_username_form}} <input type="submit" class="button" value="Search"></h4>
    </form>
    {% if found %}
    <h1 id="x3">The Username Does not exist Please Search again</h1>
    {% endif %}







{% endblock %}

templates/basic_app/user_info.html
{% extends "basic_app/base.html" %}
{% load staticfiles %}
{% block body_block %}
<div class="row">
  <div class="column side">
      <div class="jumbotron" style="background-color: white;">
        <img src="{{user_info.avatar_url}}" class="img-circle" alt="profile pic" width="200px" height="200px" id="i1">
        <h2 id="x8"><strong>{{user_info.name}}</strong></h2>
        <h3 id="x9"><ins>Public Repos:</ins>{{user_info.public_repos}} </h3>
        <h3 id="x9"><ins>Followers:</ins>{{user_info.followers}}</h3>
        <h3 id="x9"><ins>Following:</ins>{{user_info.following}}</h3>
        <br>
        <a href="https://github.com/{{user_info.login}}"><img src="https://assets-cdn.github.com/images/modules/logos_page/GitHub-Mark.png" class="img-circle" width="50px" height="50px"></a>
   </div>
 </div>
  <div class="column middle">
    <div class="panel-group">
      {% for name in repo_info %}
        <div class="list-group">
          <div class="panel-heading">
              <h3 id="x6"><a href="{% url 'basic_app:commit_history' user=name.owner.login repo_name=name.name %}">{{ name.name }}</a></h3>
          </div>
          <div class="panel-body">
            <h3 id="x2"><ins>Project Language</ins>:  {{ name.language }}</h3></li>
            <h3 id="x2"><ins>Project Link</ins>:<a href="https://github.com/{{name.owner.login}}/{{name.name}}">Click Here</a></h3>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

templates/basic_app/user_list.html
{% extends "basic_app/base.html" %}
{% load staticfiles %}
{% block body_block %}
    {% for name in user_search_list.items %}
    <div class="list-group" >
        <h2 style="background-color: white;">  <a class="list-group-item" href="{% url 'basic_app:user_profile' user=name.login  %}"><img src="{{name.avatar_url}}" class="img-circle" alt="profile pic" width="100px" height="100px">  {{ name.login }}</a></h2>
    </div>
    {% endfor %}
{% endblock %}